name: CI

on:
  push:
    branches:
      - master

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: NG_CLI_ANALYTICS=ci npm ci
      - name: Build
        run: npm run build
      - name: Publish
        run: |
          cd dist/
          npm publish
