name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Create .npmrc file
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_ACCESS_TOKEN }}" > .npmrc
      - name: Install Dependencies
        run: NG_CLI_ANALYTICS=ci npm ci
      - name: Build
        run: |
          npm run build
      - name: Publish
        run: npm publish ./dist
