name: CI

on:
  push:
    branches:
      - master

env:
  NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
  GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: NG_CLI_ANALYTICS=ci npm ci
      - name: Build
        run: |
          npm run build
      - name: Publish if version has been updated
        uses: pascalgn/npm-publish-action@51fdb4531e99aac1873764ef7271af448dc42ab4
        with:
          tag_name: 'v%s'
          tag_message: 'v%s'
          commit_pattern: "^Release (\\S+)"
        env:
          GITHUB_WORKSPACE: './dist'
          GITHUB_TOKEN: $GITHUB_ACCESS_TOKEN
          NPM_AUTH_TOKEN: $NPM_ACCESS_TOKEN
